feat: create small rake app
TaranyukK/rack-test pull request #1
Opened 2024-08-15 23:03 UTC by TaranyukK

2024-08-16 18:13 UTC, BubuntuClu requested changes

2024-08-16 18:13 UTC, BubuntuClu commented on middleware/time.rb
> +class Time
Rack приложение
Это данный класс. В его обязанности входит обработка запроса и формирование ответа в формате совместимом с rack. То есть здесь мы проверяем правильный ли пришёл URL или нужно отдать 404, хватает ли параметров или нужно отдать 400-й статус. При этом логику формирования тела ответа мы помещаем в отдельный класс бизнес логики.

Класс бизнес логики
Это отдельный простой Ruby класс, который может называться, например, TimeFormatter. Он ничего не должен знать о rack приложении, иными словами о том кто и где будет его использовать. Мы можем вызывать его из консоли или в другом Ruby приложении без HTTP API интерфейса.

2024-08-16 18:13 UTC, BubuntuClu commented on middleware/time.rb
> +  def call(env)
у тебя сейчас все смешано в один класс, он и ответы формирует и парсит строку. надо разбить на два разных

2024-08-16 18:13 UTC, BubuntuClu commented on middleware/time.rb
> +    params['format']&.split(',')&.reject { |f| TIME_FORMATS.key?(f) } || []
ты делаешь двойную итерацию по массиву параметров, сначала тут, а потом в formatted_time, не оптимально получается. надо уложится в один обход

2024-08-16 18:13 UTC, BubuntuClu commented on middleware/time.rb
> +      [400, headers, ["Unknown time format [#{invalid_formats.join(', ')}]"]]
формируй ответ используя `Rack::Response`

2024-08-19 07:09 UTC, BubuntuClu requested changes

2024-08-19 07:09 UTC, BubuntuClu commented on time_formatter.rb
> +      format_string = @format_params.map { |f| TIME_FORMATS[f] }.join('-')
https://github.com/TaranyukK/rack-test/pull/1#discussion_r1720160216
это не изменилось. вообще даже хуже стало, ты добавил еще один метод `valid?` который пробегается по массиву. результат ты не кэшируешь. при каждом вызове `invalid_formats` ты проходишься по массиву
ты все еще дважды обходишь массив `format_params`. получи массив ошибок и правильных форматов за одно действие

2024-08-19 07:09 UTC, BubuntuClu commented on time_formatter.rb
> +  def formatted_time
метод плохо реализован, он в одном случае возвращает строку, во втором `nil`. разный тип данных получается

разбей его на 3 метода. заполнение массивов, получение строки времени, получение ошибок

2024-08-19 07:09 UTC, BubuntuClu commented on middleware/path_validator.rb
> +      [404, { 'Content-Type' => 'text/plain' }, ['Not Found']]
что-то этот ответ выбивается от других. а зачем разделять `PathValidator` и `Time` классы?

2024-08-19 07:09 UTC, BubuntuClu commented on middleware/time.rb
> +      response = Rack::Response.new(formatter.formatted_time, 200, headers)
вынеси формирование ответа в отдельный метод. в него передавай нужные параметры. и внутри уже формируй Rack::Response

2024-08-19 17:34 UTC, BubuntuClu requested changes

2024-08-19 17:34 UTC, BubuntuClu commented on time_formatter.rb
> +    @valid_formats, @errors = resolve_formats
у тебя получился ниндзя метод. кроме инициализации ты начинаешь тут логику какую-то выполнять. так нельзя делать

сделай `initialize/call/valid?/time_string/invalid_string` методы. и их используй в классе выше

2024-08-19 17:34 UTC, BubuntuClu commented on time_formatter.rb
> +    format_string = @valid_formats.map { |format| TIME_FORMATS[format] }.join('-')
почему бы тебе сразу не сохранить значение из хэша в строку валидных форматов? тогде тебе в методе этом надо будет только джоин сделать и приведение ко времени

2024-08-19 17:34 UTC, BubuntuClu commented on time_formatter.rb
> +    format_string = @valid_formats.map { |format| TIME_FORMATS[format] }.join('-')
сейсчас же ты о5 по массиву бегаешь второй раз

2024-08-19 17:34 UTC, BubuntuClu commented on time_formatter.rb
> +    errors = []
похоже на то что надо объявлять в инициализации
метод инициализации как раз нужен чтобы объявлить начальные параметры

2024-08-19 17:34 UTC, BubuntuClu commented on middleware/time.rb
> +    @env = env
1- почему это инстанс переменная?
2- она нигде не используется

2024-08-20 14:23 UTC, VidgarVii requested changes

2024-08-20 14:23 UTC, VidgarVii commented on app.rb
> +class App
данный класс ни чего полезного не делает. Можно его полностью удалить. А в config ru указать Time как приложение, а не middleware

2024-08-20 14:23 UTC, VidgarVii commented on app.rb
> +    { 'Content-Type' => 'text/plain' }
Для настройки ContentType по умолчанию можно воспользоваться настройкой через Rack::ContentType

https://www.rubydoc.info/gems/rack/Rack/ContentType

и этот код будет не нужным

2024-08-20 14:23 UTC, VidgarVii commented on middleware/time.rb
> +    if env['PATH_INFO'] == '/time'
проверку path можно делегировать на утилиту Rack::URLMap. Он как раз будет возвращать 404, если путь не верен

```ruby
require_relative 'time_app'
ROUTES = {
  '/time' => TimeApp.new
}


run Rack::URLMap.new(ROUTES)
```

2024-08-20 14:23 UTC, VidgarVii commented on time_formatter.rb
> +  def valid?
Идея с методами верная, но реализация нет. Для работы с данным объектом нужна целая инструкция, а это плохо. Это уже не делает его привычным нам объектом из реального мира. А просто какой-то набор методов, которые надо вызывать в нужном порядке.
ООП говорит, что публичные методы можно вызывать в любом порядке и от этого не должно быть каких то багов и изменение внутреннего состояния объекта. (Если это конечно не конечный автомат. Но и там есть решение)

Сейчас если после new вызывать например valid? или time_string то будет ошибка. А вот конструкция объекта об этом не говорит. Что методы надо вызывать в какой-то последовательностью. Вот этой последовательности не должно быть.
Чтобы исправить. Надо сделать так чтобы метод call возвращал такой объект, который будет содержать все нужные методы и данные. С которым будет работать констроллер.
Самый просто вариант использовать структуру
https://ruby-doc.org/core-2.5.0/Struct.html

2024-08-21 07:22 UTC, merged